// Auto-generated by tools/build_scenes.py - DO NOT EDIT MANUALLY
#pragma once
#include <Arduino.h>
#include <pgmspace.h>

struct KubiScene {
    const char* id;
    const char* title;
    uint16_t width;      // Source width (e.g. 120)
    uint16_t height;     // Source height (e.g. 160)
    uint8_t scale;       // Integer scale factor (e.g. 2 for 240x320)
    uint8_t paletteSize;
    const uint16_t* palette;
    uint32_t rleLength;  // Total bytes in rleData (count, index pairs)
    const uint8_t* rleData;
};

extern const KubiScene scene_beach_eating_ice_cream;
extern const KubiScene scene_birthday;
extern const KubiScene scene_christmas;
extern const KubiScene scene_laying_in_flower_field;
extern const KubiScene scene_music;
extern const KubiScene scene_sitting_by_cafe;
extern const KubiScene scene_sleeping_in_bed;
extern const KubiScene scene_watching_sunset;
extern const KubiScene scene_working_from_home;
extern const KubiScene scene_working_out_at_gym;

extern const KubiScene* const ALL_KUBI_SCENES[];
extern const size_t ALL_KUBI_SCENE_COUNT;
