// Auto-generated by tools/build_sprites.py - DO NOT EDIT MANUALLY
#pragma once
#include <Arduino.h>
#include <pgmspace.h>

struct KubiSpriteAnimation {
    const char* name;
    uint16_t width;
    uint16_t height;
    uint16_t frameCount;
    uint16_t frameDelayMs;
    const uint16_t* const* frames;
};

// Animation: kubi_bounce (40x40, 3 frames)
extern const KubiSpriteAnimation anim_kubi_bounce;

extern const KubiSpriteAnimation* const ALL_KUBI_ANIMATIONS[];
extern const size_t ALL_KUBI_ANIMATION_COUNT;
