#!/usr/bin/env python3
"""
build_scenes.py — Converts placeholder scenes into RLE-compressed RGB565 arrays for Kubi.

Takes 240x320 images from art/Scaled Down/, downsamples to 120x160 with 32-color
palette quantization (Artist Guide Option B), and encodes them as RLE byte streams.
When drawn on screen, each pixel is scaled 2x integer nearest-neighbor to fill 240x320.
Total flash footprint for all 10 scenes is under 200 KB!
"""

import os
import glob
import re
from pathlib import Path
from PIL import Image

try:
    SCRIPT_DIR = Path(__file__).resolve().parent
except NameError:
    # PlatformIO SCons context: working directory is firmware/
    SCRIPT_DIR = (Path.cwd() / "tools").resolve()

FIRMWARE_DIR = SCRIPT_DIR.parent
PROJECT_ROOT = FIRMWARE_DIR.parent
SCALED_DIR = PROJECT_ROOT / "art" / "Scaled Down"
INCLUDE_DIR = FIRMWARE_DIR / "include"
SRC_DIR = FIRMWARE_DIR / "src"

HEADER_FILE = INCLUDE_DIR / "KubiScenes.h"
SOURCE_FILE = SRC_DIR / "KubiScenes.cpp"

def to_rgb565(r, g, b):
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5

def sanitize_name(name):
    clean = re.sub(r'[^a-zA-Z0-9_]', '_', name.lower())
    clean = re.sub(r'_+', '_', clean).strip('_')
    return clean

def build():
    if not SCALED_DIR.exists():
        print(f"[SCENE_BUILDER] Error: {SCALED_DIR} does not exist!")
        return

    images = sorted(glob.glob(str(SCALED_DIR / "*.*")))
    if not images:
        print(f"[SCENE_BUILDER] No images found in {SCALED_DIR}")
        return

    scenes = []

    print(f"[SCENE_BUILDER] Found {len(images)} placeholder image(s). Processing...")

    for img_path in images:
        path = Path(img_path)
        base_name = path.stem
        # Format friendly title: strip 'Kubi - ' prefix if present
        title = base_name.replace("Kubi - ", "").strip()
        var_name = sanitize_name(title)

        im = Image.open(img_path).convert("RGB")
        # Half resolution (120x160) for 2x nearest-neighbor chunky pixel art
        small = im.resize((120, 160), Image.Resampling.LANCZOS)
        # Quantize to 32 colors
        q = small.quantize(colors=32, dither=Image.Dither.FLOYDSTEINBERG)
        pal_rgb = q.getpalette()[:32*3]
        pal_565 = [to_rgb565(pal_rgb[i*3], pal_rgb[i*3+1], pal_rgb[i*3+2]) for i in range(32)]
        pixels = list(q.getdata())

        # RLE encode: pairs of (count, palette_index)
        # where count is 1..255, index is 0..31
        rle_runs = []
        cur_idx = pixels[0]
        cnt = 1
        for p in pixels[1:]:
            if p == cur_idx and cnt < 255:
                cnt += 1
            else:
                rle_runs.extend([cnt, cur_idx])
                cur_idx = p
                cnt = 1
        rle_runs.extend([cnt, cur_idx])

        size_kb = (len(rle_runs) + len(pal_565) * 2) / 1024.0
        scenes.append({
            "title": title,
            "var_name": var_name,
            "width": 120,
            "height": 160,
            "scale": 2,
            "palette": pal_565,
            "rle": rle_runs,
            "size_kb": size_kb
        })
        print(f"  -> Scene '{title}': 120x160 (scale 2x) -> {len(rle_runs)//2} runs ({size_kb:.1f} KB)")

    total_kb = sum(s["size_kb"] for s in scenes)
    print(f"[SCENE_BUILDER] Total compressed size for {len(scenes)} scenes: {total_kb:.1f} KB")

    # Generate KubiScenes.h
    header_content = """// Auto-generated by tools/build_scenes.py - DO NOT EDIT MANUALLY
#pragma once
#include <Arduino.h>
#include <pgmspace.h>

struct KubiScene {
    const char* id;
    const char* title;
    uint16_t width;      // Source width (e.g. 120)
    uint16_t height;     // Source height (e.g. 160)
    uint8_t scale;       // Integer scale factor (e.g. 2 for 240x320)
    uint8_t paletteSize;
    const uint16_t* palette;
    uint32_t rleLength;  // Total bytes in rleData (count, index pairs)
    const uint8_t* rleData;
};

"""
    for s in scenes:
        header_content += f"extern const KubiScene scene_{s['var_name']};\n"

    header_content += f"""
extern const KubiScene* const ALL_KUBI_SCENES[];
extern const size_t ALL_KUBI_SCENE_COUNT;
"""

    # Generate KubiScenes.cpp
    source_content = """// Auto-generated by tools/build_scenes.py - DO NOT EDIT MANUALLY
#include "KubiScenes.h"

"""
    for s in scenes:
        vn = s["var_name"]
        # Palette array
        source_content += f"static const uint16_t palette_{vn}[] PROGMEM = {{\n"
        pal_hex = [f"0x{c:04X}" for c in s["palette"]]
        for i in range(0, len(pal_hex), 8):
            source_content += "    " + ", ".join(pal_hex[i:i+8]) + ",\n"
        source_content += "};\n\n"

        # RLE data array
        source_content += f"static const uint8_t rle_{vn}[] PROGMEM = {{\n"
        rle_hex = [f"0x{b:02X}" for b in s["rle"]]
        for i in range(0, len(rle_hex), 16):
            source_content += "    " + ", ".join(rle_hex[i:i+16]) + ",\n"
        source_content += "};\n\n"

        # Scene struct
        source_content += f"""const KubiScene scene_{vn} = {{
    "{vn}",
    "{s['title']}",
    {s['width']},
    {s['height']},
    {s['scale']},
    {len(s['palette'])},
    palette_{vn},
    {len(s['rle'])},
    rle_{vn}
}};

"""

    source_content += "const KubiScene* const ALL_KUBI_SCENES[] = {\n"
    for s in scenes:
        source_content += f"    &scene_{s['var_name']},\n"
    source_content += "};\n\n"
    source_content += f"const size_t ALL_KUBI_SCENE_COUNT = {len(scenes)};\n"

    with open(HEADER_FILE, "w", encoding="utf-8") as f:
        f.write(header_content)

    with open(SOURCE_FILE, "w", encoding="utf-8") as f:
        f.write(source_content)

    print(f"[SCENE_BUILDER] Generated {HEADER_FILE.name} and {SOURCE_FILE.name} successfully!")

if __name__ == "__main__":
    build()

# PlatformIO Extra Script Hook
try:
    Import("env")
    print("[SCENE_BUILDER] Running PlatformIO pre-build scene conversion...")
    build()
except NameError:
    pass
