[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Fix the Serial Monitor Gibberish
monitor_speed = 115200

; Tell PlatformIO to use network uploading
upload_protocol = espota
; Use the mDNS name. If your router blocks mDNS, use the raw IP address here instead (e.g., 10.15.34.66)
upload_port = sunrise.local

; Tell PlatformIO to manage these specific libraries automatically
lib_deps = 
    SPI
	Wire
	fastled/FastLED @ ^3.6.0
	adafruit/Adafruit TSL2591 Library @ ^1.4.5
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	esp32async/ESPAsyncWebServer @ ^3.10.3
	bblanchon/ArduinoJson @ ^7.4.3
    ; tzapu/WiFiManager @ ^2.0.17